name: zNxPiglinRush
version: '${project.version}'
main: dev.znxki.zNxPiglinRush.ZNxPiglinRush
api-version: '26.1.2'
folia-supported: true
description: Increases Zombified Piglin spawn rate on magma blocks for gold farms
authors:
  - zNxki_
