name: zNxPiglinRush
version: '${project.version}'
main: dev.znxki.zNxPiglinRush.PiglinRushPlugin
api-version: '26.1.2'
folia-supported: true
description: Multi-block Nether spawner framework with stats, heatmap, waves and loot injection
authors: [ zNxki ]
website: https://github.com/zNxki/zNxPiglinRush
softdepend: [ PlaceholderAPI ]

commands:
  piglinrush:
    description: zNxPiglinRush main command
    usage: /piglinrush <reload|info|stats|heatmap|diagnostics|toggle>
    aliases: [ pr, znxpiglinrush ]
    permission: piglinrush.admin

permissions:
  znxpiglinrush.admin:
    description: Access to zNxPiglinRush admin commands
    default: op